### ISSUE TITLE
openpyxl overwriting

### ISSUE THREAD

**Issue by Dark-error-Honor** [Dark-error-Honor/Python#1]
My issue is in code2.py,

So the data already gets added on the right column, but it overwrites all the time so i want it to skip the row if there already is data in there

`

**Comment by Rexogamer** [comment]
On what column does it rewrite? If the second column I might have an idea how to fix it.

**Comment by Dark-error-Honor** [comment]
overwrites at row 6 and column 4

**Comment by Dark-error-Honor** [comment]
and its in excel so its column D that is starts
