### ISSUE TITLE
skip the row if there already is data in there

### ISSUE THREAD

**Issue by WK-GiHu** [Dark-error-Honor/Python#2]
You are doing:
https://github.com/Dark-error-Honor/Python/blob/3ca2bc6a49150afd9294871bfb2352687fde40c8/code2.py#L62
You don't need to iterate the Columns.

https://github.com/Dark-error-Honor/Python/blob/3ca2bc6a49150afd9294871bfb2352687fde40c8/code2.py#L64
Why do you start a new Row iteration?

https://github.com/Dark-error-Honor/Python/blob/3ca2bc6a49150afd9294871bfb2352687fde40c8/code2.py#L65

>only add the data when name and surname column are empty

### Please confirm:
- [x] Column `name` is index `4`
- [x] Column `surname` is index `5`
- [ ] Other

**Comment by WK-GiHu** [comment]
```
for cell in ws.iter_rows(min_row=5, min_col=4, max_col=5, max_row=ws.max_row - 9):
    # cell == (Column 4 - name, Column 5 - surname)
    if all((c.value is None for c in cell)):
        print('empty')

        # cell[0].row is the current Row
        row_index = cell[0].row
        column_index_to_start = 4

        for col_index, value in enumerate((voornaam, achternaam, mg, mgh, mk, mkh, pg, pgh, pk, pkh, brood, betaald), column_index_to_start):
            ws.cell(row=row_index, column=col_index).value = value
        break
```

**Comment by Dark-error-Honor** [comment]
> You are doing:
> https://github.com/Dark-error-Honor/Python/blob/3ca2bc6a49150afd9294871bfb2352687fde40c8/code2.py#L62
> 
> 
> You don't need to iterate the Columns.
> https://github.com/Dark-error-Honor/Python/blob/3ca2bc6a49150afd9294871bfb2352687fde40c8/code2.py#L64
> 
> 
> Why do you start a new Row iteration?
> https://github.com/Dark-error-Honor/Python/blob/3ca2bc6a49150afd9294871bfb2352687fde40c8/code2.py#L65
> 
> > only add the data when name and surname column are empty
> 
> ### Please confirm:
> * [x]  Column `name` is index `4`
> * [ ]  Column `surname` is index `5`
> * [ ]  Other

**Comment by Dark-error-Honor** [comment]
I start a new row iteration because some rows dont contain a name only a surname.
and

**Comment by WK-GiHu** [comment]
> some rows dont contain a name only a surname.

My proposal match both cells in **one** loop, no second loop necessary.
Give it a try and update your [`code2.py`](https://github.com/Dark-error-Honor/Python/blob/master/code2.py) accordinly so i can review your changes.

**Comment by Dark-error-Honor** [comment]
ok so now it goes to the bottom of the excel but it still overwrites at the bottom
at row 53

**Comment by WK-GiHu** [comment]
You have indentation error, starting at Line 60 up to Line 70
https://github.com/Dark-error-Honor/Python/blob/4b67591d77aa7781e026a20c627e2df028b94619/code2.py#L60
...
https://github.com/Dark-error-Honor/Python/blob/4b67591d77aa7781e026a20c627e2df028b94619/code2.py#L70

**Comment by Dark-error-Honor** [comment]
whoops pasted it wrong
